=== Gurung-Manish/Car-E-com/Development/catalog_18029108.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!--Defining root tag vehicleShop-->
	<xs:element name="vehicleShop">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="shopDetails"/>
				<xs:element ref="vehicle"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="shopDetails">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="logo"/>
				<xs:element ref="sname"/>
				<xs:element ref="address"/>
				<xs:choice>
					<xs:element name="ZIPcode" type="xs:integer"/>
					<xs:element name="postalCode" type="xs:integer"/> 
				</xs:choice>
				<xs:element ref="phnNo"/>
				<xs:element ref="website"/>
				<xs:element ref="tagline"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="logo"/>
	<xs:element name="sname" type="xs:string"/>
	<xs:element name="address" type="xs:string"/>
	<xs:element name="phnNo" type="xs:integer"/>
	<xs:element name="website" type="xs:string"/>
	<xs:element name="tagline" type="xs:string"/>
	
	
	<!--defining vehicle tag which is inside vehicleShop tag-->
	<xs:element name="vehicle">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="car" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<!--defining car tag which is inside cars tag-->
	<xs:element name="car">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="summary"/>
			</xs:sequence>
		<xs:attribute ref="carId" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="picture">
		<xs:complexType>
			<xs:attribute name="number" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="summary" type="xs:string"/>
	<xs:attribute name="carId" type="xs:string"/>

	
	
	<!--Defining description tag which is inside car tag-->
	<xs:element name="description">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="picture"/>
				<xs:element ref="modelName"/>
				<xs:element ref="vehicleType"/>
				<xs:element ref="brand"/>
				<xs:element ref="color"/>
				<xs:element ref="mileage"/>
				<xs:element ref="fuelType"/>
				<xs:element ref="fuelCapacity"/>
				<xs:choice>
					<xs:element name="cc" type="xs:integer"/>
					<xs:element name="powerOutput" type="xs:integer"/> 
				</xs:choice>
				<xs:element ref="horsepower"/>
				<xs:element ref="transmission"/>
				<xs:element ref="seat"/>
				<xs:element ref="wheelDrive"/>
				<xs:element ref="odometerReading"/>
				<xs:element ref="quantity"/>
				<xs:element ref="price"/>
				<xs:element ref="dimension"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="quantity" type="xs:integer"/>
	<xs:element name="odometerReading">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="distanceUnit" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="price">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="priceUnit" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="modelName" type="xs:string"/>
	<xs:element name="color" type="xs:string"/>
	<xs:element name="horsepower" type="xs:integer"/>
	<xs:element name="dimension">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="length" type="xs:string"/>
				<xs:element name="width" type="xs:string"/>
				<xs:element name="height" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="vehicleType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Sedan" />
				<xs:enumeration value="SUV" />
				<xs:enumeration value="Hatchback" />
				<xs:enumeration value="Sports" />
				<xs:enumeration value="Van" />
				<xs:enumeration value="Luxury" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="brand">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Toyota"/>
				<xs:enumeration value="Maruti"/>
				<xs:enumeration value="Datsun"/>
				<xs:enumeration value="Nissan"/>
				<xs:enumeration value="Suzuki"/>
				<xs:enumeration value="Volkswagen"/>
				<xs:enumeration value="Honda"/>
				<xs:enumeration value="Tata"/>
				<xs:enumeration value="Hyundai"/>
				<xs:enumeration value="Ford"/>
				<xs:enumeration value="Tesla"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="wheelDrive">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="4 Wheeldrive"/>
				<xs:enumeration value="Front Wheeldrive"/>
				<xs:enumeration value="Rear Wheeldrive"/>
				<xs:enumeration value="Full Wheeldrive"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="fuelCapacity">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unit" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="mileage">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unit" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fuelType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Petrol"/>
				<xs:enumeration value="Diesel"/>
				<xs:enumeration value="Hybrid"/>
				<xs:enumeration value="Electric"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="transmission">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Manual"/>
				<xs:enumeration value="Automatic"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="seat">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minExclusive value="1"/>
				<xs:maxExclusive value="20"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Gurung-Manish/Car-E-com/Development/catalog_18029108.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_18029108.css"?>
<vehicleShop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="catalog_18029108.xsd">
	<shopDetails>
		<logo></logo>	
		<sname>HAMRO GADI</sname>
		<address>Simalchaur, Pokara-8</address>
		<postalCode>3300</postalCode>
		<phnNo>06155789</phnNo>
		<website>www.nepaliautomobile.com</website>
		<tagline>"Car for all"</tagline>
	</shopDetails>
	<vehicle>
		<car carId="0011">
			<description>
				<picture number="1"></picture>
				Model Name: <modelName>Ford EcoSport</modelName>
				Vehicle Type: <vehicleType>SUV</vehicleType>
				Brand: <brand>Ford</brand>
				Color: <color>Moondust Silver</color>	
				Mileage:<mileage unit="kmpl">21.7</mileage>
				Fuel Type:<fuelType>Diesel</fuelType>
				Fuel Capacity:<fuelCapacity unit="litre">52</fuelCapacity>
				CC:<cc>1498</cc>
				Horsepower:<horsepower>116</horsepower>
				Transmission:<transmission>Manual</transmission>
				Seat: <seat>5</seat>
				Wheeldrive: <wheelDrive>4 Wheeldrive</wheelDrive>
				Distance Covered: <odometerReading distanceUnit="km">10000</odometerReading>
				Quantity: <quantity>2</quantity>
				Price: <price priceUnit="NPR">3500000</price>
				Dimension:<dimension>
					<length>157.4 inches (L)</length>
					<width>69.49 inches(W)</width>
					<height>64.84 inches(H)</height>
				</dimension>
			</description>
			
			<summary>The 2020 EcoSport is designed to help you move freely. Its compact size and available 
			Intelligent 4WD are perfect for maneuvering new terrains. No matter where you go, EcoSport comes 
			prepared and in style with a comfortable interior and intelligent technology to help you take on the world.</summary>
		</car>
		
		<car carId="0022">
			<description>
				<picture number="2"></picture>
				Model Name: <modelName>Ford EcoSport</modelName>
				Vehcile Type: <vehicleType>SUV</vehicleType>
				Brand: <brand>Ford</brand>
				Color: <color>Lightning Blue</color>
				Mileage: <mileage unit="kmpl">500</mileage>
				Fuel Type: <fuelType>Petrol</fuelType>
				Fuel Capacity: <fuelCapacity unit="litre">52</fuelCapacity>
				CC: <cc>1498</cc>
				Horsepower: <horsepower>116</horsepower>
				Transmission: <transmission>Manual</transmission>
				Seat: <seat>5</seat>
				Wheeldrive: <wheelDrive>4 Wheeldrive</wheelDrive>
				Distance Covered: <odometerReading distanceUnit="km">15000</odometerReading>
				Quantity: <quantity>1</quantity>
				Price: <price priceUnit="NPR">3400000</price>
				Dimension:<dimension>
					<length>157.4 inches (L)</length>
					<width>69.49 inches (W)</width>
					<height>64.84 inches (H)</height>
				</dimension>
			</description>
			<summary>The 2020 EcoSport is designed to help you move freely. Its compact size and available 
			Intelligent 4WD are perfect for maneuvering new terrains. No matter where you go, EcoSport comes 
			prepared and in style with a comfortable interior and intelligent technology to help you take on the world.</summary>
		</car>
		
		<car carId="0123">
			<description>
				<picture number="3"></picture>
				Model Name: <modelName>Toyota Hiace</modelName>
				Vehicle Type: <vehicleType>Van</vehicleType>
				Brand: <brand>Toyota</brand>
				Color: <color>White Pearl Crystal Shine -CH</color>
				Mileage: <mileage unit="kmpl">12</mileage>
				Fuel Type: <fuelType>Diesel</fuelType>
				Fuel Capacity: <fuelCapacity unit="litre">65</fuelCapacity>
				CC: <cc>2982</cc>
				Horsepower: <horsepower>503</horsepower>
				Transmission: <transmission>Manual</transmission>
				Seat: <seat>5</seat>
				Wheeldrive: <wheelDrive>Rear Wheeldrive</wheelDrive>
				Distance Covered:<odometerReading distanceUnit="km">20000</odometerReading>
				Quantity: <quantity>2</quantity>
				Price: <price priceUnit="NPR">10800000</price>
				Dimension:<dimension>
					<length>208.6 inches (L)</length>
					<width>74.01 inches (W)</width>
					<height>89.9 inches (H)</height>
				</dimension>
			</description>
			<summary>Toyota Hiace Commuter Bus is virtually a luxury coach! With individual bucket seats and two 
			seater bench seats throughout. When you drive for a living, there's no room in the operating budget 
			for a vehicle that's expensive to run. That's why the Hiace boasts low running costs. </summary>
		</car>
		
		<car carId="0124">
			<description>
				<picture number="4"></picture>
				Model Name: <modelName>Tesla Model S</modelName>
				Vehicle Type: <vehicleType>Luxury</vehicleType>
				Brand: <brand>Tesla</brand>
				Color: <color>Red</color>
				Mileage: <mileage unit="kmpc">400</mileage>
				Fuel Type: <fuelType>Electric</fuelType>
				Fuel Capacity: <fuelCapacity unit="kWh">75</fuelCapacity>
				Power Output: <powerOutput>825</powerOutput>
				Horsepower: <horsepower>259</horsepower>
				Transmission: <transmission>Automatic</transmission>
				Seat: <seat>5</seat>
				Wheeldrive: <wheelDrive>Full Wheeldrive</wheelDrive>
				Distance Covered: <odometerReading distanceUnit="km">20000</odometerReading>
				Quantity: <quantity>2</quantity>
				Price: <price priceUnit="NPR">10800000</price>
				Dimension:<dimension>
					<length>208.6 inches (L)</length>
					<width>74.01 inches (W)</width>
					<height>89.9 inches (H)</height>
				</dimension>
			</description>
			<summary>Model S sets an industry standard for performance and safety. 
			Tesla’s all-electric powertrain delivers unparalleled performance in all weather conditions.Model S can get you 
			anywhere you want to go—with industry-leading range and convenient charging options, all over the world.</summary>
		</car>
		
		<car carId="0155">
			<description>
				<picture number="5"></picture>
				Model Name: <modelName>Baleno</modelName>
				Vehicle Type: <vehicleType>Hatchback</vehicleType>
				Brand: <brand>Maruti</brand>
				Color: <color>Nexa Blue</color>
				Mileage: <mileage unit="kmpl">27.4</mileage>
				Fuel Type: <fuelType>Diesel</fuelType>
				Fuel Capacity: <fuelCapacity unit="l">37</fuelCapacity>
				CC: <cc>1248</cc>
				Horsepower: <horsepower>109</horsepower>
				Transmission: <transmission>Manual</transmission>
				Seat: <seat>5</seat>
				Wheeldrive: <wheelDrive>Front Wheeldrive</wheelDrive>
				Distance Covered: <odometerReading distanceUnit="km">20000</odometerReading>
				Quantity: <quantity>2</quantity>
				Price: <price priceUnit="NPR">3200000</price>
				Dimension:<dimension>
					<length>157 inches (L)</length>
					<width>69 inches (W)</width>
					<height>60 inches (H)</height>
				</dimension>
			</description>
			<summary>Some notable features on offer are a 7.0-inch touchscreen infotainment system, Smartplay 
			Studio App with Apple CarPlay and Android Auto, automatic climate control, steering-mounted audio controls,
			LED projector headlamps, 16-inch alloy wheels, dual airbags, ABS+EBD, seatbelts with pretensioner and force limiters, 
			and ISOFIX mounts. In terms of features, Maruti Suzuki has changed the touchscreen on the top-spec Alpha variant.</summary>
		</car>
		
		<car carId="0666">
			<description>
				<picture number="6"></picture>
				Model Name: <modelName>Datson Go</modelName>
				Vehicle Type: <vehicleType>Hatchback</vehicleType>
				Brand: <brand>Datsun</brand>
				Color: <color>Amber Orange</color>
				Mileage: <mileage unit="kmpl">20.1</mileage>
				Fuel Type: <fuelType>Petrol</fuelType>
				Fuel Capacity: <fuelCapacity unit="l">37</fuelCapacity>
				CC: <cc>1198</cc>
				Horsepower: <horsepower>68</horsepower>
				Transmission: <transmission>Manual</transmission>
				Seat: <seat>5</seat>
				Wheeldrive: <wheelDrive>Front Wheeldrive</wheelDrive>
				Distance Covered: <odometerReading distanceUnit="km">30000</odometerReading>
				Quantity: <quantity>3</quantity>
				Price: <price priceUnit="NPR">1900000</price>
				Dimension:<dimension>
					<length>150 inches (L)</length>
					<width>64.3 inches (W)</width>
					<height>58.4 inches (H)</height>
				</dimension>
			</description>
			<summary>Some notable features on offer are a 7.0-inch touchscreen infotainment system, Smartplay 
			Studio App with Apple CarPlay and Android Auto, automatic climate control, steering-mounted audio controls,
			LED projector headlamps, 16-inch alloy wheels, dual airbags, ABS+EBD, seatbelts with pretensioner and force limiters, 
			and ISOFIX mounts. In terms of features, Maruti Suzuki has changed the touchscreen on the top-spec Alpha variant.</summary>
		</car>
		
		<car carId="0277">
			<description>
				<picture number="7"></picture>
				Model Name: <modelName>Volkswagen Polo</modelName>
				Vehicle Type: <vehicleType>Hatchback</vehicleType>
				Brand: <brand>Volkswagen</brand>
				Color: <color>Carbon Steel</color>
				Mileage: <mileage unit="kmpl">21.4</mileage>
				Fuel Type: <fuelType>Diesel</fuelType>
				Fuel Capacity: <fuelCapacity unit="l">45</fuelCapacity>
				CC: <cc>1498</cc>
				Horsepower: <horsepower>68</horsepower>
				Transmission: <transmission>Manual</transmission>
				Seat: <seat>5</seat>
				Wheeldrive: <wheelDrive>Front Wheeldrive</wheelDrive>
				Distance Covered: <odometerReading distanceUnit="km">25000</odometerReading>
				Quantity: <quantity>5</quantity>
				Price: <price priceUnit="NPR">2400000</price>
				Dimension:<dimension>
					<length>150 inches (L)</length>
					<width>64.3 inches (W)</width>
					<height>58.4 inches (H)</height>
				</dimension>
			</description>
			<summary>The Polo Treandline has been designed to give you the essentioals of what makes a Volkswagen.
			Made using the best of German engeneering, the Polo Trendline variant features many sagety and technology featiures
			like dual front airbags, ABS, front disc brakes and much more.</summary>
		</car>
		
		<car carId="0118">
			<description>
